
function f = theGym(X,Y,N,L)

% Solve a Pattern Recognition Problem with a Neural Network
% Script generated by NPRTOOL
%
% This script assumes these variables are defined:
%
%   X - input data.
%   Y - target data.

inputs = transpose(X);
targets = transpose(Y);

% Create a Pattern Recognition Network
hiddenLayerSize = N;
net = patternnet(hiddenLayerSize);


% Set up Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio = 20/100;
net.divideParam.testRatio = 10/100;
% net.numLayers = L;
% if size(N,2) ~= 1
%     for i = 1:size(N)
%         net.layers{i}.size = N(i);
%     end
% end
% Train the Network
[net,tr] = train(net,inputs,targets,'useParallel','yes');

% Test the Network
outputs = net(inputs);
errors = gsubtract(targets,outputs);
performance = perform(net,targets,outputs);
f = {net,tr,errors,performance};

% Plots
% Uncomment these lines to enable various plots.
% view(net)
% figure, plotperform(tr)
% figure, plottrainstate(tr)
% figure, plotconfusion(targets,outputs)
% figure, ploterrhist(errors)

end